version: "3.8"

networks:
  echall-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.39
    container_name: echall-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_USERNAME= ${DB_ROOT_USERNAME}
      - MYSQL_ROOT_PASSWORD= ${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - echall-network
  redis:
    image: redis:latest
    container_name: echall-redis
    ports:
      - "6379:6379"
    networks:
      - echall-network
  mongo:
    image: mongo:latest
    container_name: echall-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: [ "--bind_ip", "0.0.0.0" ]
    volumes:
      - ./mongodb:/data/db
    networks:
      - echall-network

  # OpenSearch 서비스 (노드 1)
  opensearch-node1:
    image: opensearchproject/opensearch:2.17.0
    container_name: echall-opensearch-node1
    environment:
      - discovery.type=single-node # 단일 노드 설정
      - bootstrap.memory_lock=true # 메모리 잠금 활성화
      - plugins.security.disabled=true # username, password 필요 X
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m # JVM 메모리 설정 (512MB)
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPEN_SEARCH_ROOT_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/opensearch-data:/usr/share/opensearch/data # OpenSearch 데이터 저장소
    ports:
      - "9200:9200" # REST API 포트 매핑
      - "9600:9600" # 내부 모니터링 포트 매핑
    networks:
      - echall-network

  # OpenSearch Dashboards 서비스 (UI)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.0
    container_name: echall-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # username, password 필요 X
    ports:
      - "5601:5601" # Dashboards UI 포트 매핑
    networks:
      - echall-network

  # LocalStack - S3 로컬 테스트
  localstack:
    image: localstack/localstack:latest
    container_name: echall-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/data/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./data/localstack:/data/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - echall-network