version: "3.8"

name: echall-dev

networks:
  echall-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.39
    container_name: echall-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USERNAME=${LOCAL_DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - echall-network
  redis:
    image: redis:latest
    container_name: echall-redis
    ports:
      - "6379:6379"
    networks:
      - echall-network
  mongo:
    image: mongo:latest
    container_name: echall-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${LOCAL_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
    command: [ "--bind_ip", "0.0.0.0" ]
    volumes:
      - ./mongodb:/data/db
    networks:
      - echall-network

