spring:
  config:
    import:
      - optional:file:.env[.properties]
    activate:
      on-profile: dev

  datasource:
    url: ${MY_DEV_DATA_SOURCE}
    username: ${DB_ROOT_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: 6379
      password: ${DB_ROOT_PASSWORD}
      username: default


    mongodb:
      uri: ${MONGO_DEV_URI}
      database: ${MONGO_DATABASE}
      username: ${DB_ROOT_USERNAME}
      password: ${DB_MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MY_GOOGLE_CLIENT_ID}
            client-secret: ${MY_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${MY_GOOGLE_DEV_REDIRECT_URI}
            scope:
              - email
              - profile
#              - https://www.googleapis.com/auth/youtube.force-ssl
#              - https://www.googleapis.com/auth/youtube.readonly
          kakao:
            client-id: ${MY_KAKAO_CLIENT_ID}
            client-secret: ${MY_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${MY_KAKAO_DEV_REDIRECT_URI}
            client-name: kakao
          naver:
            client-id: ${MY_NAVER_CLIENT_ID}
            client-secret: ${MY_NAVER_CLIENT_SECRET}
            redirect-uri: ${MY_NAVER_DEV_REDIRECT_URI}
            authorization-grant-type: authorization_code
      success:
        redirect-uri: ${OAUTH2_SUCCESS_DEV_REDIRECTION_PATH}

nlp:
  model:
    word2vec: ${WORD2VEC_MODEL_FILE_PATH}

perplexity:
  api-key: ${PERPLEXITY_API_KEY}
  base-url: https://api.perplexity.ai

opensearch:
  host: ${OPEN_SEARCH_DEV_HOST}
  port: ${OPEN_SEARCH_AWS_PORT}
  protocol: ${OPEN_SEARCH_HTTPS_PROTOCOL}
  username: ${OPEN_SEARCH_ROOT_USERNAME}
  password: ${OPEN_SEARCH_ROOT_PASSWORD}