spring:
  config:
    import:
      - optional:file:.env[.properties]
    activate:
      on-profile: prod
  
  datasource:
    url: ${MY_DATA_SOURCE}
    username: ${DB_ROOT_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:

    redis:
      host: 127.0.0.1
      port: 6379
      password: ${DB_ROOT_PASSWORD}
      username: default


    mongodb:
      uri: ${MONGO_URI}
      database: admin
      username: ${DB_ROOT_USERNAME}
      password: ${DB_MYSQL_PASSWORD}
