spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/echall_local_db
    username: ${DB_ROOT_USERNAME}
    password: ${DB_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:

    redis:
      host: 127.0.0.1
      port: 6379
      password: ${DB_ROOT_PASSWORD}
      username: default


    mongodb:
      uri: ${MONGO_URI}
      database: admin
      username: ${DB_ROOT_USERNAME}
      password: ${DB_ROOT_PASSWORD}