spring:
  config:
    import:
      - optional:file:.env[.properties]
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:mysql://english-platform.c58u6yego0wp.ap-southeast-2.rds.amazonaws.com:3306/echall_local_db
    username: ${DB_ROOT_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:

    redis:
      host: 127.0.0.1
      port: 6379
      password: ${DB_ROOT_PASSWORD}
      username: default


    mongodb:
      uri: ${MONGO_URI}
      database: admin
      username: ${DB_ROOT_USERNAME}
      password: ${DB_ROOT_PASSWORD}