name: Deploy to EC2

on:
  push:
    branches:
      - deploy  # 병합할 브랜치 이름 (예: main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy JAR to EC2
        env:
          KEY_PATH: ${{ secrets.KEY_PATH }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -i "$KEY_PATH" build/libs/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/

      - name: Restart application on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          sudo systemctl stop myapp || true
          sudo systemctl start myapp
          EOF
